### ISSUE TITLE
Logs for calibration and testing of ZR300

### ISSUE THREAD

**Issue by mauricefallon** [ethz-asl/mav_dji_ros_interface#15] opened 2017-09-03 20:04 UTC
From Maurice:
To get started with this I would like to use the RealSense Z300. Do you have any logs and configuration files with that sensor?

From Inkyu:
In order to use Realsense ZR300 (Z300?) with MSF and Rovio presented in the work, you need to calibration it carefully.
I didn’t get what the logs imply but all configuration files are located at
https://github.com/ethz-asl/mav_dji_ros_interface/tree/master/dji_interface/cfg/raven

**Comment by mauricefallon** [comment] 2017-09-03 20:06
Just to re-phrase: Could you please provide a ROS bag of a log/dataset of the ZR300 for calibration and a datalog of it in an experiment

**Comment by inkyusa** [comment] 2017-09-07 09:04
Dear, Mauricefallon
Please have a look our wiki page, https://github.com/ethz-asl/mav_dji_ros_interface/wiki/Sensor-Calibration, for ZR300 calibration. We also provide ROSbag dataset that used for this project.
If this answer resolves your questions, please close this issue.
Best.

**Comment by mauricefallon** [comment] 2017-09-12 15:56
Hi @inkyusa, I've spent a big amount of time trying to get Rovio to work with the calibration ROSbag -
 without any success. (It works just fine with the MH01 log)

When I run Rovio when playing this bagfile, the processing is really slow - at about 1fps. (But the data is at 30fps). The feature patches drawn in the opencv UI are mostly unstable - with red boxes and huge ellipses (in yellow).

I'm using the imu '/falcon2/imu/compensated'. Have you been able to get this log to work with Rovio yourself?

**Comment by ZacharyTaylor** [comment] 2017-09-12 17:54
Hi, just thought I would add my input. If the processing drops down to 1 fps this usually means ROVIO has diverged and can no longer find any features to track. This can happen for a large number of reasons, one possibility is if the rovio_filter.info file is missing or contains an invalid entry rovio will try to generate a new one with default values and run off this instead. However, these defaults generally won't fit the camera and IMU. Easiest way to check if this is the issue is to turn frame visualization off in the config. If you still get it visualizing, rovio is not actually finding/using your config file.

Another possible problem is that the bias terms for the IMU were incorrectly estimated. This can be an issue for the realsense cameras as their IMU is right at the lower end of what rovio can work with. I recently got ROVIO up and running on an Intel Euclid which seemed to have an even worse IMU then the ZR300s I had previously used. My rovio .config file had to have much much higher bias values to get the estimates to remain stable. You can see the parameters I used here https://gist.github.com/ZacharyTaylor/3fb8dc125e5a84b15333b595cb37690c

**Comment by mauricefallon** [comment] 2017-09-13 17:23
@ZacharyTaylor , that's awesome, thanks a lot! It was generating a new info file and not reading the intended one. All is fine now. 

@inkyusa  I needed to add a velocity block to the [rovio config block](https://github.com/ethz-asl/mav_dji_ros_interface/blob/master/dji_interface/cfg/raven/rovio_filter.info)

VelocityUpdate
{
    UpdateNoise
    {
        vel_0 0.0001
        vel_1 0.0001
        vel_2 0.0001
    }
    MahalanobisTh0 7.689997599999999
    qAM_x 0
    qAM_y 0
    qAM_z 0
    qAM_w 1
}

[this video might be useful to other newbies](https://www.dropbox.com/s/ox5rxjqav29flql/2017-09-rovio-realsense-zr300.ogv?dl=0)

**Comment by fmina** [comment] 2017-09-13 17:52
@mauricefallon Indeed, this velocity update block is new and we have to add it to rovio filter info.
See #16 

Thanks!

**Closed** 2017-09-13 17:52 UTC

**Comment by mauricefallon** [comment] 2017-09-22 10:53
Hi @inkyusa , sorry to bother you again on this issue. The rosbag you provided for your zr300 contains IMU data at 200Hz.

My own zr300 outputs at 430Hz. I can't see any flag for setting it to publish at 200 nor a setting in the driver or rovio. Is it necessary to correct for this or is rovio smart enough?

**Comment by ZacharyTaylor** [comment] 2017-09-22 20:12
The zr300 asynchronously outputs acceleration data at 250 hz and gyro data at 200 hz. The official driver just dumps this all into one message stream and from memory also doesn't bother timestamping it correctly. You need to use our fork where we stick the data into one message and sync it with the system clock.
